### PR TITLE
chore: fix indexed keyword issue in events

### PR DESCRIPTION
**Pull request by sujithsomraaj**

### CODE REVIEW

**Comment by vikramarun** [comment]
It looks like the only remaining places uint256[] indexed is used is in `RescueProposed` and `CrossChainInitiatedWithdrawMulti`

**Review by vikramarun — COMMENTED** [review]
It looks like the only remaining places uint256[] indexed is used is in `RescueProposed` and `CrossChainInitiatedWithdrawMulti`

**Review by vikramarun — APPROVED** [review]
lgtm

**Review by 0xTimepunk — APPROVED** [review]
LGTM

**Pull request merged**
